# development:
#   server: "http://localhost:9292/faye"
#   secret_token: "secret"
# test:
#   server: "http://localhost:9292/faye"
#   secret_token: "secret"


production:
  server: "http://fayerservermike.herokuapp.com/faye"
  secret_token: "b97428d8c0f24ce83374dc6a777dc9d2b1a36d53fb32f14b8ea774f3f26732df"
  signature_expiration: 86400 # one day
